apiVersion: oadp.openshift.io/v1alpha1
kind: DataProtectionApplication
metadata:
  name: velero-sample
  namespace: openshift-adp
spec:
  backupLocations:
  - velero:
      config:
        profile: default
        region: us-east-1
        s3ForcePathStyle: 'true'
        s3Url: 'https://s3.eu-de.cloud-object-storage.appdomain.cloud' #update this
      credential:
        key: cloud
        name: cloud-credentials
      default: true
      objectStorage:
        bucket: odf-rglj9w-bucket-oadp #update this
        prefix: velero
      provider: aws
  configuration:
    nodeAgent:
      enable: true
      uploaderType: restic
    velero:
      defaultPlugins:
      - openshift
      - aws
      - csi
